[workspace]

members = [
	"streaming-platform",
	#"sp-tokio-tls",
	"sp-dto",
	"sp-auth",
	"sp-cfg",
	"sp-web",
	"sp-yew",
	"sp-manager",
	"co/sp-pack-core",
	"co/spcohub",
	"co/spcobuild",
	"co/spcopod",
	"co/spcoweb",
	"distribution/sp-public-host",
	"distribution/spup"
]