[workspace]

members = [
	"streaming-platform",
	#"sp-tokio-tls",
	"sp-dto",
	"sp-auth",
	"sp-cfg",
	"sp-web",
	"sp-yew",
	"sp-manager",
	"distribution/sp-pack-core",
	"distribution/sp-build",
	"distribution/sp-public-host",
	"distribution/sp-hub",
	"distribution/sp-file-svc",
	"distribution/spup"
]