[package]
name = "streaming-platform"
version = "0.1.0"
authors = ["Maximb <sprayrules@gmail.com>"]
edition = "2018"

[dependencies]

log = "*"
ws = { version = "*", features = ["ssl"] }
openssl = "*"
url = "*"
