[package]
name = "streaming-platform"
version = "0.1.0"
authors = ["Maximb <sprayrules@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = "*"
bytes = "*"
futures = { version = "0.3.0", features = ["async-await"] }
serde = "*"
serde_derive = "*"
serde_json = "*"
toml = "*"
tokio = { version = "0.2", features = ["full"] }
hyper = { version = "*", optional = true }
sp-dto = { path = "../sp-dto" }

[features]

default = []
http = ["hyper"]
