[package]
name = "streaming-platform"
version = "0.1.0"
authors = ["Maximb <sprayrules@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["message", "broker", "stream"]
categories = ["network-programming", "asynchronous"]
repository = "https://github.com/astromq/streaming-platform"
documentation = "https://docs.rs/streaming-platform"
description = """
Data streaming platform and message broker with concurrent data transfer capabilities.
"""
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = "*"
bytes = "*"
futures = { version = "0.3", features = ["async-await"] }
rand = "*"
siphasher = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
toml = "*"
tokio = { version = "0.2", features = ["full"] }
hyper = { version = "0.13", optional = true }
sp-dto = { path = "../sp-dto" }

[features]

default = []
http = ["hyper"]

[dev-dependencies]
env_logger = "*"