[package]
name = "sp-yew"
version = "0.1.0"
authors = ["Maximb <sprayrules@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

failure = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
stdweb = "*"
yew = { git = "https://github.com/DenisKolodin/yew" }
sp-dto = { path = "../sp-dto" }
